# SwiftLint configuration
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - VibeMeter
  - VibeMeterTests

# Paths to exclude
excluded:
  - Pods
  - Derived
  - .build
  - .swiftpm
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData

# Disabled rules
disabled_rules:
  - trailing_whitespace # SwiftFormat handles this
  - todo # We want to keep TODOs
  - line_length # We'll use SwiftFormat's line length instead
  - function_body_length # Can be too restrictive
  - type_body_length # Can be too restrictive
  - file_length # Can be too restrictive
  - identifier_name # Can be too restrictive for single letter names in some contexts

# Opt-in rules
opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Rule configurations
force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning

large_tuple:
  warning: 3
  error: 4

trailing_comma:
  mandatory_comma: false

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  no_print_statements:
    name: "Print statements"
    regex: '^\s*print\('
    message: "Use LoggingService instead of print statements"
    severity: warning